services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: acc-calc-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AccCalc123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - acc-calc-network
    restart: unless-stopped

  backend:
    build:
      context: ./NetCoreBackend
      dockerfile: Dockerfile
    container_name: acc-calc-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - acc-calc-network
    restart: unless-stopped

  frontend:
    build:
      context: ./VueFrontend
      dockerfile: Dockerfile
    container_name: acc-calc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - acc-calc-network
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local

networks:
  acc-calc-network:
    driver: bridge
